dist: trusty
sudo: required
language: php
php:
  - '7.1.0'

branches:
  only:
    - develop

script:
  - composer install
  - composer config repositories.kkrieger85 vcs https://github.com/JeroenVanLeusden/Bannerslider-Magento2
  - composer require magestore/module-bannerslider:dev-patch-1
