dist: trusty
sudo: required
language: php
php:
  - '7.0.0'

branches:
  only:
    - develop

script:
  - composer install
  - composer config repositories.kkrieger85 vcs https://github.com/kkrieger85/Bannerslider-Magento2
  - composer require magestore/module-bannerslider:dev-maste
